config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	validates :email, :session_token, presence: true, uniqueness: true
	validates :password_digest, presence: true
	validates :password, length: { minimum: 1, allow_nil: true }
	after_initialize :ensure_session_token
	attr_reader :password
	
	def random_session_token
		SecureRandom::urlsafe_base64(16)
	end
	
	def ensure_session_token
		self.session_token ||= random_session_token
	end
	
	def reset_session_token!
		self.session_token = random_session_token
		self.save!
		self.session_token
	end
	
	def password= password
		@password = password
		self.password_digest = BCrypt::Password.create(password)
	end
	
	def is_password? password
		BCrypt::Password.new(self.password_digest).is_password? password
	end
	
	def self.find_by_credentials email, password
		user = User.find_by(email: email)
		user && user.is_password?(password) ? user : nil
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	helper_method :current_user
	
	def log_in_user! user
		@current_user = user
		session[:session_token] = user.reset_session_token!
		redirect_to user_url(user)
	end
	
	def current_user
		return nil if session[:session_token].nil?
		@current_user ||= User.find_by(session_token: session[:session_token])
	end
	
	def logged_in?
		!current_user.nil?
	end
	
	def not_logged_in
		redirect_to new_session_url if !logged_in?
	end
	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
		render :new
	end
	
	def create
		user = User.find_by_credentials(params[:user][:email],
			params[:user][:password])
		if user.nil?
			render :new
		else
			log_in_user! user
		end
	end
	
	def destroy
		if !current_user.nil?
			current_user.reset_session_token!
			session[:session_token] = nil
			redirect_to new_session_url
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
		render :new
	end
	
	def create
		user = User.new user_params
		if user.save
			log_in_user! user
		else
			redirect_to new_user_url
		end
	end
	
	def show
		@user = User.find(params[:id])
		render :show
	end
	
	private
	
	def user_params
		params.require(:user).permit(:email, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def auth_token
		"<input type='hidden' name='authenticity_token' 
			value='#{h(form_authenticity_token)}' />".html_safe
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Issue Tracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <header>
		<h2>Issue Tracker</h2>
		<div>
			<% if current_user.nil? %>
				<a href='<%= new_session_url %>'>Sign In</a>
				<a href='<%= new_user_url %>'>Sign Up</a>
			<% else %>
				<ul>
					<li>Logged in as: <%= current_user.email %></li>
					<li><form action="<%= session_url %>" method="post">
							<%= auth_token %>
							<input type="hidden" name="_method" value="delete" />
							<input type="submit" value="Sign Out &rarr;" />
						</form></li>
				</ul>
			<% end %>
		</div>
	</header>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="post">
	<%= auth_token %>
	<label for='email'>Email</label><br>
	<input type="text" name="user[email]" id="email" /><br>
	<br>
	<label for='password'>Password</label><br>
	<input type="password" name="user[password]" id="password" /><br>
	<br>
	<input type="submit" value="Create Account &rarr;" />
</form>

app/views/users/show.html.erb
<h1>Profile of <%= @user.email %></h1>

Email: <%= @user.email %>